### ISSUE TITLE
bioformats schema not installed

### ISSUE THREAD

**Issue by keithschulze** [mytardis/mytardisbf#3]
@whettenhj reported that bioformats.json schema is not installed correctly when MyTardis starts up. Appears that the fixtures package is not found. As @whettenhj points out:
It seems that "include_package_data=True" in setup.py is not 100% reliable for installing Python modules from source, at least when using Python 2.7.3 (the system Python version on Store.Monash-Test's Ubuntu 12).  Here's a StackOverflow discussion on this matter: http://stackoverflow.com/questions/7522250/how-to-include-package-data-with-setuptools-distribute

**Comment by grischa** [comment]
Edit: not related, I think. Creating separate issue.
@dean-taylor encountered a possibly related issue.
When migrating the database with the app installed the loading of the app happens before the migration. However, in `apps.py`, there is a query, which hits a database that's not migrated yet and it fails with table not found.
You could wrap it in `try: except django.db.utils.ProgrammingError:` maybe?
Then it would continue the migration and set up the schema when the server starts
